version: '3'

volumes:
  pgdata:

networks:
  default:

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: michalhosna/adminer
    container_name: adminer
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
    environment:
      # specify service name of PostgreSQL to ADMINER_SERVER
      - ADMINER_SERVER=db
      - ADMINER_DRIVER=pgsql
      - ADMINER_DB=${DB_NAME:-db}
      - ADMINER_USERNAME=${DB_USER:-postgres}
      - ADMINER_PASSWORD=${DB_PASSWORD:-postgres}
      - ADMINER_NAME=ADMINER for PostgreSQL DB
## uncommnet to enable auto-login
#      - ADMINER_AUTOLOGIN=1

  gw:
    image: spring-msa/gateway
    container_name: gw
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - CONTAINER_NAME=gw
      - PORT=5000
      - DISCOVERY=http://sd:3001/eureka/,http://sd2:3002/eureka/
      - JAEGER_HTTP_URL=http://jaeger:14268/api/traces
    ports:
      - "5000:5000"
  sd:
    image: spring-msa/eureka
    container_name: sd
    build:
      context: ./discovery
      dockerfile: Dockerfile
    environment:
      - CONTAINER_NAME=sd
      - PORT=3001
      - ZONE=http://sd2:3002/eureka/
    ports:
      - "3001:3001"

  sd2:
    image: spring-msa/eureka
    container_name: sd2
    environment:
      - CONTAINER_NAME=sd2
      - PORT=3002
      - ZONE=http://sd:3001/eureka/
    ports:
      - "3002:3002"

  account:
    image: spring-msa/account-api
    container_name: account
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      - CONTAINER_NAME=account
      - PORT=9001
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWD=${DB_PASSWORD:-postgres}
      - DB_URL=${DB_URL:-r2dbc:postgresql://db:5432/db}
      - DISCOVERY=http://sd:3001/eureka/,http://sd2:3002/eureka/
      - JAEGER_HTTP_URL=http://jaeger:14268/api/traces
    networks:
      - default

  account2:
    image: spring-msa/account-api
    container_name: account2
    ports:
      - "9002:9002"
    depends_on:
      - db
    environment:
      - CONTAINER_NAME=account2
      - PORT=9002
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWD=${DB_PASSWORD:-postgres}
      - DB_URL=${DB_URL:-r2dbc:postgresql://db:5432/db}
      - DISCOVERY=http://sd:3001/eureka/,http://sd2:3002/eureka/
      - JAEGER_HTTP_URL=http://jaeger:14268/api/traces
    networks:
      - default

  account3:
    image: spring-msa/account-api
    container_name: account3
    ports:
      - "9003:9003"
    depends_on:
      - db
    environment:
      - CONTAINER_NAME=account3
      - PORT=9003
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWD=${DB_PASSWORD:-postgres}
      - DB_URL=${DB_URL:-r2dbc:postgresql://db:5432/db}
      - DISCOVERY=http://sd:3001/eureka/,http://sd2:3002/eureka/
      - JAEGER_HTTP_URL=http://jaeger:14268/api/traces
    networks:
      - default

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaegar
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - default

